National legal base
bitzesty/trade-tariff-frontend pull request #272
Opened 2020-12-14 14:33 UTC by myxrome

[Asana Card](https://app.asana.com/0/1199164317302737/1198719959859936)
* added info about the national legal base.

2020-12-14 14:59 UTC, RyanMacG approved these changes

2020-12-14 15:03 UTC, matthewford requested changes
We might need an additional ENV var flag -  as this can't be deployed to production right now, we need to keep the previous behaviour unless an env var is set.

The timeline first they will hide the legal base, then once DIT have the data in the information_text, an env var to display this data.

2020-12-15 12:51 UTC, myxrome commented
> We might need an additional ENV var flag - as this can't be deployed to production right now, we need to keep the previous behaviour unless an env var is set.
> 
> The timeline first they will hide the legal base, then once DIT have the data in the information_text, an env var to display this data.

hey, @matthewford I've fixed as described.

2020-12-15 12:52 UTC, matthewford approved these changes

2020-12-18 17:39 UTC, merged